server:
  port: 7900
spring:
  application:
    name: cloud-user
  cloud:
    config:
      env: dev
      label: master
      discovery:
        enabled: true
        serviceId: cloud-configserver
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/
